//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAP.Foliacion.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AsignacionInventario
    {
        public int Id { get; set; }
        public int IdBanco { get; set; }
        public int IdNombrePersona { get; set; }
        public int FoliosAsignados { get; set; }
        public int FolioInicial { get; set; }
        public int FolioFinal { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
    
        public virtual Tbl_CuentasBancarias Tbl_CuentasBancarias { get; set; }
        public virtual Tbl_NombresPersonal Tbl_NombresPersonal { get; set; }
    }
}
